### ISSUE TITLE
build errors with flutter_svg when upgrading to 1.20

### ISSUE THREAD

**Issue by M1Joe** [xsahil03x/fancy_on_boarding#35]
I upgraded to Flutter 1.20 and could no longer build my project.  I believe that it's because of the dependency on flutter_svg: ^0.17.4

For anyone running into this problem, you can fix it by adding the following to your pubspec.yaml:
```
dependency_overrides:
  flutter_svg: ^0.18.0
```

**Comment by vytautas-pranskunas-** [comment]
any updates on this package without ovverides?

**Comment by vytautas-pranskunas-** [comment]
this is not solving my issue.. iget another error which they are talking about here:
https://github.com/flutter/flutter/issues/63038
this also related to flutter_svg

**Comment by vytautas-pranskunas-** [comment]
Is this package dead? any updates?

**Comment by Strain-solutions** [comment]
dependency_overrides:  fixed it for me, but I've a feeling it was a lucky escape...

**Comment by jpbassinello** [comment]
Same here =/

**Comment by Retnuh1337** [comment]
This fixed the problem for me:

```
dependency_overrides:
  flutter_svg: ^0.18.0
```

**Comment by xsahil03x** [comment]
Fixed in #37

**Comment by vytautas-pranskunas-** [comment]
When new package version will be relase  ecause i still see 1.6.0 and with 1.6.0 this issue was not fixed

**Comment by xsahil03x** [comment]
@vytautas-pranskunas-  v1.7.0 released.
